In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
def csv_to_parquet(csv_path, save_name):
    df = pd.read_csv(csv_path)
    df.to_parquet(f'./{save_name}.parquet')
    del df
    gc.collect()
    print(save_name, 'Done.')

In [3]:
path = 'jeju_traffic.csv'

jeju = pd.read_csv(path)

jeju

,Unnamed: 0,day_of_week,base_hour,road_in_use,lane_count,road_rating,multi_linked,connect_code,maximum_speed_limit,weight_restricted,...,road_type,start_latitude,start_longitude,start_turn_restricted,end_latitude,end_longitude,end_turn_restricted,target,성수기,자동차총보유대수
0,0,1,17,0,1,106,0,0,60.0,32400.0,...,3,33.427747,126.662612,0,33.427749,126.662335,0,52.0,0,100.000000
1,1,1,21,0,2,103,0,0,60.0,0.0,...,0,33.500730,126.529107,1,33.504811,126.526240,0,30.0,1,100.000000
2,2,4,7,0,2,103,0,0,80.0,0.0,...,0,33.279145,126.368598,0,33.280072,126.362147,0,61.0,0,105.000000
3,3,0,13,0,2,107,0,0,50.0,0.0,...,0,33.246081,126.567204,0,33.245565,126.566228,0,20.0,0,335.000000
4,4,6,8,0,2,103,0,0,80.0,0.0,...,0,33.462214,126.326551,0,33.462677,126.330152,0,38.0,0,100.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4698971,4698971,1,16,0,1,107,0,0,50.0,0.0,...,0,33.422145,126.278125,0,33.420955,126.273750,0,20.0,0,263.761062
4698972,4698972,1,2,0,2,107,0,0,80.0,43200.0,...,3,33.472505,126.424368,0,33.472525,126.424890,0,65.0,0,263.761062
4698973,4698973,3,22,0,2,103,0,0,60.0,0.0,...,0,33.447183,126.912579,0,33.444121,126.912948,0,30.0,0,263.761062
4698974,4698974,2,2,0,2,103,0,0,80.0,0.0,...,0,33.443596,126.431817,0,33.444996,126.433332,0,73.0,0,263.761062
4698975,4698975,6,6,0,2,107,0,0,60.0,0.0,...,0,33.256785,126.508940,0,33.257130,126.510364,0,35.0,0,263.761062

In [4]:
path = 'test1.csv'

test = pd.read_csv(path)

test

,Unnamed: 0,day_of_week,base_hour,lane_count,road_rating,multi_linked,connect_code,maximum_speed_limit,weight_restricted,height_restricted,road_type,start_latitude,start_longitude,start_turn_restricted,end_latitude,end_longitude,end_turn_restricted,성수기,자동차총보유대수
0,0,1,17,3,107,0,0,70.0,0.0,0.0,0,33.499427,126.541298,0,33.500772,126.543837,1,1,100.000000
1,1,6,12,2,103,0,0,70.0,0.0,0.0,3,33.258507,126.427003,0,33.258119,126.415840,0,1,100.000000
2,2,0,2,1,103,0,0,60.0,0.0,0.0,0,33.258960,126.476508,0,33.259206,126.474687,0,1,105.000000
3,3,1,23,3,103,0,0,70.0,0.0,0.0,0,33.473494,126.545647,0,33.471061,126.545467,0,1,335.000000
4,4,2,17,3,106,0,0,70.0,0.0,0.0,0,33.501477,126.569223,0,33.496863,126.581230,0,1,100.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
291236,291236,5,5,1,103,0,0,80.0,0.0,0.0,0,33.472819,126.463030,0,33.470483,126.460846,0,1,263.761062
291237,291237,0,20,2,103,0,0,60.0,0.0,0.0,0,33.305359,126.598914,0,33.300796,126.600332,0,1,263.761062
291238,291238,0,11,1,107,0,0,30.0,0.0,0.0,0,33.493624,126.496769,1,33.497500,126.496946,1,1,263.761062
291239,291239,0,7,2,107,0,0,60.0,0.0,0.0,0,33.254782,126.507014,0,33.255659,126.507333,0,1,263.761062
291240,291240,0,10,3,106,0,0,70.0,0.0,0.0,0,33.246996,126.524358,0,33.247053,126.523503,0,1,263.761062

In [5]:
# pip install tune-sklearn ray[tune]

In [6]:
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import VotingRegressor , GradientBoostingRegressor
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from ray import tune
from tune_sklearn import TuneSearchCV

In [9]:
target = 'target'

x = jeju.drop(target, axis = 1)
y = jeju[target]

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.3)

In [10]:
print(x_train.shape)
print(x_test.shape)

(3289283, 20)
(1409693, 20)

In [15]:
params = {'learning_rate': [0.1, 0.5], 'max_depth':[4,8,12,16,20], 'min_samples_leaf': [10,30,60,90,120], 'min_samples_split':[30,60,90,120], 'subsample':[0.5,0.8,1]}

model = GradientBoostingRegressor(loss = 'ls', random_state=42 , verbose = 0)

model_GT = TuneSearchCV(model, params, cv = 5, refit = True, sk_n_jobs=1, n_jobs=5, verbose = 2, max_iters=10 ,pipeline_auto_early_stop=True)

model_GT.fit(x_train, y_train)

NameError: name 'X' is not defined

In [11]:
y_pred_GT = model_GT.predict(test)

C:\Users\User\AppData\Roaming\Python\Python38\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but SGDClassifier was fitted without feature names
  warnings.warn(

ValueError: X has 19 features, but SGDClassifier is expecting 100 features as input.

In [12]:
sample_submission = pd.read_csv('sample_submission.csv')
sample_submission

sample_submission[target] = tune_search
sample_submission.to_csv('GridianBooster2.csv', index = False)

In [ ]:
pd.read_csv('GridianBooster1.csv')